/**
 * CAEN Rev.2 code descriptions (most common codes).
 * Source: clasificarecaen.ro / ONRC public data
 */
const CAEN_CODES: Record<string, string> = {
  "0111": "Cultivarea cerealelor (excluzând orezul), plantelor leguminoase și a plantelor producătoare de semințe oleaginoase",
  "0112": "Cultivarea orezului",
  "0113": "Cultivarea legumelor și a pepenilor, a rădăcinoaselor și tuberculilor",
  "0119": "Cultivarea altor plante din culturi nepermanente",
  "0121": "Cultivarea strugurilor",
  "0141": "Creșterea bovinelor de lapte",
  "0142": "Creșterea altor bovine",
  "0150": "Activități în ferme mixte (cultură vegetală combinată cu creșterea animalelor)",
  "0161": "Activități auxiliare pentru producția vegetală",
  "0210": "Silvicultură și alte activități forestiere",
  "0220": "Exploatarea forestieră",
  "0311": "Pescuitul maritim",
  "0321": "Acvacultură maritimă",
  "1011": "Prelucrarea și conservarea cărnii",
  "1013": "Fabricarea produselor din carne (inclusiv din carne de pasăre)",
  "1020": "Prelucrarea și conservarea peștelui, crustaceelor și moluștelor",
  "1039": "Prelucrarea și conservarea fructelor și legumelor n.c.a.",
  "1051": "Fabricarea produselor lactate și a brânzeturilor",
  "1061": "Fabricarea produselor de morărit",
  "1071": "Fabricarea pâinii; fabricarea prăjiturilor și a produselor proaspete de patiserie",
  "1072": "Fabricarea biscuiților și pișcoturilor; fabricarea prăjiturilor și a produselor conservate de patiserie",
  "1082": "Fabricarea produselor din cacao, a ciocolatei și a produselor zaharoase",
  "1101": "Distilarea, rafinarea și mixarea băuturilor alcoolice",
  "1102": "Fabricarea vinurilor din struguri",
  "1105": "Fabricarea berii",
  "1107": "Producția de băuturi răcoritoare nealcoolice; producția de ape minerale și alte ape îmbuteliate",
  "1310": "Pregătirea fibrelor și filarea fibrelor textile",
  "1392": "Fabricarea de articole confecționate din textile (cu excepția îmbrăcămintei și lenjeriei de corp)",
  "1413": "Fabricarea altor articole de îmbrăcăminte (exclusiv lenjeria de corp)",
  "1520": "Fabricarea încălțămintei",
  "1610": "Tăierea și rindeluirea lemnului",
  "1621": "Fabricarea de furnire și a panourilor din lemn",
  "1623": "Fabricarea altor elemente de dulgherie și tâmplărie, pentru construcții",
  "1629": "Fabricarea altor produse din lemn; fabricarea articolelor din plută, paie și din alte materiale vegetale împletite",
  "1711": "Fabricarea celulozei",
  "1712": "Fabricarea hârtiei și a cartonului",
  "1721": "Fabricarea hârtiei și a cartonului ondulat și a ambalajelor din hârtie și carton",
  "1812": "Alte activități de tipărire n.c.a.",
  "1920": "Fabricarea produselor obținute din prelucrarea țițeiului",
  "2011": "Fabricarea gazelor industriale",
  "2016": "Fabricarea materialelor plastice în forme primare",
  "2041": "Fabricarea săpunurilor, detergenților și a produselor de întreținere",
  "2042": "Fabricarea parfumurilor și a produselor cosmetice (de toaletă)",
  "2120": "Fabricarea preparatelor farmaceutice",
  "2211": "Fabricarea anvelopelor și a camerelor de aer; reșaparea și refacerea anvelopelor",
  "2219": "Fabricarea altor produse din cauciuc",
  "2222": "Fabricarea articolelor de ambalaj din material plastic",
  "2229": "Fabricarea altor produse din material plastic",
  "2312": "Prelucrarea și fasonarea sticlei plate",
  "2332": "Fabricarea cărămizilor, țiglelor și altor produse pentru construcții, din argilă arsă",
  "2361": "Fabricarea produselor din beton pentru construcții",
  "2399": "Fabricarea altor produse din minerale nemetalice n.c.a.",
  "2410": "Producția de metale feroase sub forme primare și de feroaliaje",
  "2511": "Fabricarea de construcții metalice și părți componente ale structurilor metalice",
  "2529": "Producția de rezervoare, cisterne și containere metalice",
  "2550": "Fabricarea produselor metalice obținute prin deformare plastică; metalurgia pulberilor",
  "2562": "Operațiuni de mecanică generală",
  "2571": "Fabricarea produselor de tăiat",
  "2572": "Fabricarea articolelor de feronerie",
  "2573": "Fabricarea uneltelor",
  "2593": "Fabricarea articolelor din fire metalice; fabricarea de lanțuri și arcuri",
  "2599": "Fabricarea altor articole din metal n.c.a.",
  "2611": "Fabricarea subansamblurilor electronice (module)",
  "2612": "Fabricarea altor componente electronice",
  "2620": "Fabricarea calculatoarelor și a echipamentelor periferice",
  "2630": "Fabricarea echipamentelor de comunicații",
  "2640": "Fabricarea produselor electronice de larg consum",
  "2651": "Fabricarea de instrumente și dispozitive pentru măsură, verificare, control, navigație",
  "2660": "Fabricarea de echipamente pentru iradierea, electromedicalele și electroterapeutice",
  "2711": "Fabricarea motoarelor, generatoarelor și transformatoarelor electrice și a aparatelor de distribuție și control al electricității",
  "2712": "Fabricarea aparatelor de distribuție și control al electricității",
  "2720": "Fabricarea de acumulatori și baterii",
  "2732": "Fabricarea altor fire și cabluri electrice și electronice",
  "2740": "Fabricarea de echipamente electrice de iluminat",
  "2751": "Fabricarea de aparate electrocasnice",
  "2811": "Fabricarea de motoare și turbine (cu excepția celor pentru avioane, autovehicule și motociclete)",
  "2822": "Fabricarea echipamentelor de ridicat și manipulat",
  "2825": "Fabricarea echipamentelor de ventilație și refrigerare, exclusiv a echipamentelor de uz casnic",
  "2829": "Fabricarea altor mașini și utilaje de utilizare generală n.c.a.",
  "2830": "Fabricarea mașinilor și utilajelor pentru agricultură și silvicultură",
  "2841": "Fabricarea utilajelor și a mașinilor-unelte pentru prelucrarea metalelor",
  "2849": "Fabricarea altor mașini-unelte n.c.a.",
  "2893": "Fabricarea utilajelor pentru prelucrarea produselor alimentare, băuturilor și tutunului",
  "2899": "Fabricarea altor mașini și utilaje specifice n.c.a.",
  "2910": "Fabricarea autovehiculelor de transport rutier",
  "2920": "Producția de caroserii pentru autovehicule; fabricarea de remorci și semiremorci",
  "2932": "Fabricarea altor piese și accesorii pentru autovehicule și pentru motoare de autovehicule",
  "3011": "Construcția de nave și structuri plutitoare",
  "3030": "Fabricarea de aeronave și nave spațiale",
  "3101": "Fabricarea de mobilă pentru birouri și magazine",
  "3102": "Fabricarea de mobilă pentru bucătării",
  "3109": "Fabricarea de mobilier n.c.a.",
  "3250": "Fabricarea de dispozitive, aparate și instrumente medicale și stomatologice",
  "3311": "Repararea articolelor fabricate din metal",
  "3312": "Repararea mașinilor",
  "3313": "Repararea echipamentelor electronice și optice",
  "3314": "Repararea echipamentelor electrice",
  "3320": "Instalarea mașinilor și echipamentelor industriale",
  "3511": "Producția de energie electrică",
  "3512": "Transportul energiei electrice",
  "3513": "Distribuția energiei electrice",
  "3514": "Comercializarea energiei electrice",
  "3521": "Producția gazelor",
  "3522": "Distribuția combustibililor gazoși, prin conducte",
  "3530": "Furnizarea de abur și aer condiționat",
  "3600": "Captarea, tratarea și distribuția apei",
  "3700": "Colectarea și epurarea apelor uzate",
  "3811": "Colectarea deșeurilor nepericuloase",
  "3812": "Colectarea deșeurilor periculoase",
  "3821": "Tratarea și eliminarea deșeurilor nepericuloase",
  "3822": "Tratarea și eliminarea deșeurilor periculoase",
  "3831": "Demontarea (dezasamblarea) mașinilor și a echipamentelor scoase din uz pentru recuperarea materialelor",
  "3832": "Recuperarea materialelor reciclabile sortate",
  "3900": "Activități și servicii de decontaminare",
  "4110": "Dezvoltare (promovare) imobiliară",
  "4120": "Lucrări de construcții a clădirilor rezidențiale și nerezidențiale",
  "4211": "Lucrări de construcții a drumurilor și autostrăzilor",
  "4221": "Lucrări de construcții a proiectelor utilitare pentru fluide",
  "4222": "Lucrări de construcții a proiectelor utilitare pentru electricitate și telecomunicații",
  "4291": "Construcții hidrotehnice",
  "4311": "Lucrări de demolare a construcțiilor",
  "4312": "Lucrări de pregătire a terenului",
  "4321": "Lucrări de instalații electrice",
  "4322": "Lucrări de instalații sanitare, de încălzire și de aer condiționat",
  "4329": "Alte lucrări de instalații pentru construcții",
  "4331": "Lucrări de ipsoserie",
  "4332": "Lucrări de tâmplărie și dulgherie",
  "4333": "Lucrări de pardosire și placare a pereților",
  "4334": "Lucrări de vopsitorie, zugrăveli și montări de geamuri",
  "4339": "Alte lucrări de finisare",
  "4391": "Lucrări de învelitori, șarpante și terase la construcții",
  "4399": "Alte lucrări speciale de construcții n.c.a.",
  "4511": "Comerț cu autoturisme și autovehicule ușoare (sub 3,5 tone)",
  "4519": "Comerț cu alte autovehicule",
  "4520": "Întreținerea și repararea autovehiculelor",
  "4531": "Comerț cu ridicata de piese și accesorii pentru autovehicule",
  "4532": "Comerț cu amănuntul de piese și accesorii pentru autovehicule",
  "4611": "Intermedieri în comerțul cu materii prime agricole, animale vii, materii prime textile și cu semifabricate",
  "4619": "Intermedieri în comerțul cu produse diverse",
  "4621": "Comerț cu ridicata al cerealelor, semințelor, furajelor și tutunului neprelucrat",
  "4631": "Comerț cu ridicata al fructelor și legumelor",
  "4632": "Comerț cu ridicata al cărnii și produselor din carne",
  "4634": "Comerț cu ridicata al băuturilor",
  "4639": "Comerț cu ridicata nespecializat de produse alimentare, băuturi și tutun",
  "4641": "Comerț cu ridicata al produselor textile",
  "4642": "Comerț cu ridicata al îmbrăcămintei și încălțămintei",
  "4643": "Comerț cu ridicata al aparatelor electrice de uz gospodăresc, al aparatelor de radio și televizoarelor",
  "4645": "Comerț cu ridicata al produselor cosmetice și de parfumerie",
  "4646": "Comerț cu ridicata al produselor farmaceutice",
  "4647": "Comerț cu ridicata al mobilei, covoarelor și a articolelor de iluminat",
  "4649": "Comerț cu ridicata al altor bunuri de uz gospodăresc",
  "4651": "Comerț cu ridicata al calculatoarelor, echipamentelor periferice și software-ului",
  "4652": "Comerț cu ridicata de componente și echipamente electronice și de telecomunicații",
  "4661": "Comerț cu ridicata al mașinilor agricole, echipamentelor și furniturilor",
  "4669": "Comerț cu ridicata al altor mașini și echipamente",
  "4671": "Comerț cu ridicata al combustibililor solizi, lichizi și gazoși și al produselor derivate",
  "4672": "Comerț cu ridicata al metalelor și minereurilor metalice",
  "4673": "Comerț cu ridicata al materialului lemnos și a materialelor de construcții și echipamentelor sanitare",
  "4674": "Comerț cu ridicata al echipamentelor și furniturilor de fierărie pentru instalații sanitare și de încălzire",
  "4675": "Comerț cu ridicata al produselor chimice",
  "4676": "Comerț cu ridicata al altor produse intermediare",
  "4677": "Comerț cu ridicata al deșeurilor și resturilor",
  "4690": "Comerț cu ridicata nespecializat",
  "4711": "Comerț cu amănuntul în magazine nespecializate, cu vânzare predominantă de produse alimentare, băuturi și tutun",
  "4719": "Comerț cu amănuntul în magazine nespecializate, cu vânzare predominantă de produse nealimentare",
  "4721": "Comerț cu amănuntul al fructelor și legumelor proaspete, în magazine specializate",
  "4722": "Comerț cu amănuntul al cărnii și al produselor din carne, în magazine specializate",
  "4725": "Comerț cu amănuntul al băuturilor, în magazine specializate",
  "4730": "Comerț cu amănuntul al carburanților pentru autovehicule, în magazine specializate",
  "4741": "Comerț cu amănuntul al calculatoarelor, unităților periferice și software-ului în magazine specializate",
  "4743": "Comerț cu amănuntul al echipamentelor audio/video în magazine specializate",
  "4752": "Comerț cu amănuntul al articolelor de fierărie, al articolelor din sticlă și al celor pentru vopsit, în magazine specializate",
  "4754": "Comerț cu amănuntul al articolelor și aparatelor electrocasnice, în magazine specializate",
  "4759": "Comerț cu amănuntul al mobilei, al articolelor de iluminat și al altor articole de uz casnic în magazine specializate",
  "4761": "Comerț cu amănuntul al cărților, în magazine specializate",
  "4764": "Comerț cu amănuntul al echipamentelor sportive, în magazine specializate",
  "4771": "Comerț cu amănuntul al îmbrăcămintei, în magazine specializate",
  "4772": "Comerț cu amănuntul al încălțămintei și articolelor din piele, în magazine specializate",
  "4773": "Comerț cu amănuntul al produselor farmaceutice, în magazine specializate",
  "4774": "Comerț cu amănuntul al articolelor medicale și ortopedice, în magazine specializate",
  "4775": "Comerț cu amănuntul al produselor cosmetice și de parfumerie, în magazine specializate",
  "4776": "Comerț cu amănuntul al florilor, plantelor și semințelor; comerț cu amănuntul al animalelor de companie și a hranei pentru acestea, în magazine specializate",
  "4777": "Comerț cu amănuntul al ceasurilor și bijuteriilor, în magazine specializate",
  "4778": "Comerț cu amănuntul al altor bunuri noi, în magazine specializate",
  "4779": "Comerț cu amănuntul al bunurilor de ocazie vândute prin magazine",
  "4781": "Comerț cu amănuntul al produselor alimentare, băuturilor și produselor din tutun efectuat prin standuri, chioșcuri și piețe",
  "4789": "Comerț cu amănuntul prin standuri, chioșcuri și piețe al altor produse",
  "4791": "Comerț cu amănuntul prin intermediul caselor de comenzi sau prin Internet",
  "4799": "Comerț cu amănuntul efectuat în afara magazinelor, standurilor, chioșcurilor și piețelor",
  "4910": "Transporturi interurbane de călători pe calea ferată",
  "4920": "Transporturi de marfă pe calea ferată",
  "4931": "Transporturi urbane, suburbane și metropolitane de călători",
  "4932": "Transporturi cu taxiuri",
  "4939": "Alte transporturi terestre de călători n.c.a.",
  "4941": "Transporturi rutiere de mărfuri",
  "4942": "Servicii de mutare",
  "5010": "Transporturi maritime și costiere de pasageri",
  "5020": "Transporturi maritime și costiere de marfă",
  "5110": "Transporturi aeriene de pasageri",
  "5121": "Transporturi aeriene de marfă",
  "5210": "Depozitări",
  "5221": "Activități de servicii anexe pentru transporturi terestre",
  "5224": "Manipulări",
  "5229": "Alte activități anexe transporturilor",
  "5310": "Activități poștale desfășurate sub obligativitatea serviciului universal",
  "5320": "Alte activități poștale și de curier",
  "5510": "Hoteluri și alte facilități de cazare similare",
  "5520": "Facilități de cazare pentru vacanțe și perioade de scurtă durată",
  "5530": "Parcuri pentru rulote, campinguri și tabere",
  "5590": "Alte servicii de cazare",
  "5610": "Restaurante",
  "5621": "Activități de alimentație (catering) pentru evenimente",
  "5629": "Alte servicii de alimentație n.c.a.",
  "5630": "Baruri și alte activități de servire a băuturilor",
  "5811": "Activități de editare a cărților",
  "5812": "Activități de editare de ghiduri, compendii, liste de adrese și similare",
  "5813": "Activități de editare a ziarelor",
  "5819": "Alte activități de editare",
  "5821": "Activități de editare a jocurilor de calculator",
  "5829": "Activități de editare a altor produse software",
  "5911": "Activități de producție cinematografică, video și de programe de televiziune",
  "5912": "Activități de post-producție cinematografică, video și de programe de televiziune",
  "5913": "Activități de distribuție a filmelor cinematografice, video și a programelor de televiziune",
  "5914": "Proiecția de filme cinematografice",
  "5920": "Activități de realizare a înregistrărilor audio și activități de editare muzicală",
  "6010": "Activități de difuzare a programelor de radio",
  "6020": "Activități de difuzare a programelor de televiziune",
  "6110": "Activități de telecomunicații prin rețele cu cablu",
  "6120": "Activități de telecomunicații prin rețele fără cablu (exclusiv prin satelit)",
  "6130": "Activități de telecomunicații prin satelit",
  "6190": "Alte activități de telecomunicații",
  "6201": "Activități de realizare a soft-ului la comandă (software orientat client)",
  "6202": "Activități de consultanță în tehnologia informației",
  "6203": "Activități de management (gestiune și exploatare) a mijloacelor de calcul",
  "6209": "Alte activități de servicii privind tehnologia informației",
  "6311": "Prelucrarea datelor, administrarea paginilor web și activități conexe",
  "6312": "Activități ale portalurilor web",
  "6391": "Activități ale agențiilor de știri",
  "6399": "Alte activități de servicii informaționale n.c.a.",
  "6411": "Activități ale băncii centrale (naționale)",
  "6419": "Alte activități de intermedieri monetare",
  "6420": "Activități ale holdingurilor",
  "6430": "Fonduri mutuale și alte entități financiare similare",
  "6491": "Leasing financiar",
  "6492": "Alte activități de creditare",
  "6499": "Alte intermedieri financiare n.c.a.",
  "6511": "Activități de asigurări de viață",
  "6512": "Alte activități de asigurări (exceptând asigurările de viață)",
  "6520": "Activități de reasigurare",
  "6611": "Administrarea piețelor financiare",
  "6612": "Activități de tranzacții cu valori mobiliare și mărfuri",
  "6619": "Activități auxiliare intermedierilor financiare, exclusiv activități de asigurări și fonduri de pensii",
  "6621": "Activități de evaluare a riscului de asigurare și a pagubelor",
  "6622": "Activități ale agenților și brokerilor de asigurări",
  "6629": "Alte activități auxiliare de asigurări și fonduri de pensii",
  "6630": "Activități de administrare a fondurilor",
  "6810": "Cumpărarea și vânzarea de bunuri imobiliare proprii",
  "6820": "Închirierea și subînchirierea bunurilor imobiliare proprii sau închiriate",
  "6831": "Agenții imobiliare",
  "6832": "Administrarea imobilelor pe bază de comision sau contract",
  "6910": "Activități juridice",
  "6920": "Activități de contabilitate și audit financiar; consultanță în domeniul fiscal",
  "7010": "Activități ale direcțiilor (centralelor), birourilor administrative centralizate",
  "7021": "Activități de consultanță în domeniul relațiilor publice și al comunicării",
  "7022": "Activități de consultanță pentru afaceri și management",
  "7111": "Activități de arhitectură",
  "7112": "Activități de inginerie și consultanță tehnică legate de acestea",
  "7120": "Activități de testări și analize tehnice",
  "7211": "Cercetare-dezvoltare în biotehnologie",
  "7219": "Cercetare-dezvoltare în alte științe naturale și inginerie",
  "7220": "Cercetare-dezvoltare în științe sociale și umaniste",
  "7311": "Activități ale agențiilor de publicitate",
  "7312": "Servicii de reprezentare media",
  "7320": "Activități de studiere a pieței și de sondare a opiniei publice",
  "7410": "Activități de design specializat",
  "7420": "Activități fotografice",
  "7430": "Activități de traducere scrisă și orală (interpreți)",
  "7490": "Alte activități profesionale, științifice și tehnice n.c.a.",
  "7500": "Activități veterinare",
  "7711": "Activități de închiriere și leasing cu autoturisme și autovehicule rutiere ușoare",
  "7712": "Activități de închiriere și leasing cu autovehicule rutiere grele",
  "7721": "Activități de închiriere și leasing cu bunuri recreaționale și echipament sportiv",
  "7722": "Închirierea de casete video și discuri (CD-uri, DVD-uri)",
  "7729": "Activități de închiriere și leasing cu alte bunuri personale și gospodărești n.c.a.",
  "7731": "Activități de închiriere și leasing cu mașini și echipamente agricole",
  "7732": "Activități de închiriere și leasing cu mașini și echipamente pentru construcții",
  "7733": "Activități de închiriere și leasing cu mașini și echipamente de birou (inclusiv calculatoare)",
  "7739": "Activități de închiriere și leasing cu alte mașini, echipamente și bunuri tangibile n.c.a.",
  "7740": "Leasing cu bunuri intangibile (exclusiv financiare)",
  "7810": "Activități ale agențiilor de plasare a forței de muncă",
  "7820": "Activități de contractare, pe baze temporare, a personalului",
  "7830": "Servicii de furnizare și management a forței de muncă",
  "7911": "Activități ale agențiilor turistice",
  "7912": "Activități ale tur-operatorilor",
  "7990": "Alte servicii de rezervare și asistență turistică",
  "8010": "Activități de protecție și gardă",
  "8020": "Activități de servicii privind sistemele de securizare",
  "8110": "Activități combinate de întreținere a facilităților",
  "8121": "Activități generale de curățenie a clădirilor",
  "8122": "Activități specializate de curățenie",
  "8129": "Alte activități de curățenie",
  "8130": "Activități de întreținere peisagistică",
  "8211": "Activități combinate de secretariat",
  "8219": "Activități de fotocopiere, de pregătire a documentelor și alte activități specializate de secretariat",
  "8220": "Activități ale centrelor de intermediere telefonică (call center)",
  "8230": "Activități de organizare a expozițiilor, târgurilor și congreselor",
  "8291": "Activități ale agențiilor de colectare și ale birourilor (oficiilor) de raportare a creditului",
  "8292": "Activități de ambalare",
  "8299": "Alte activități de servicii suport pentru întreprinderi n.c.a.",
  "8411": "Servicii de administrație publică generală",
  "8510": "Învățământ preșcolar",
  "8520": "Învățământ primar",
  "8531": "Învățământ secundar general",
  "8532": "Învățământ secundar, tehnic sau profesional",
  "8541": "Învățământ superior non-universitar",
  "8542": "Învățământ superior universitar",
  "8551": "Învățământ în domeniul sportiv și recreațional",
  "8552": "Învățământ în domeniul cultural (limbi străine, muzică, teatru, dans, arte plastice etc.)",
  "8553": "Școli de conducere (pilotaj)",
  "8559": "Alte forme de învățământ n.c.a.",
  "8560": "Activități de servicii suport pentru învățământ",
  "8610": "Activități de asistență spitalicească",
  "8621": "Activități de asistență medicală generală",
  "8622": "Activități de asistență medicală specializată",
  "8623": "Activități de asistență stomatologică",
  "8690": "Alte activități referitoare la sănătatea umană",
  "8710": "Activități ale centrelor de îngrijire medicală",
  "8720": "Activități ale centrelor de recuperare psihică și de dezintoxicare, exclusiv spitale",
  "8730": "Activități ale căminelor de bătrâni și ale căminelor pentru persoane aflate în incapacitate de a se îngriji singure",
  "8790": "Alte activități de asistență socială, cu cazare n.c.a.",
  "8810": "Activități de asistență socială, fără cazare, pentru bătrâni și pentru persoane cu dizabilități",
  "8891": "Activități de îngrijire zilnică pentru copii",
  "8899": "Alte activități de asistență socială, fără cazare n.c.a.",
  "9001": "Activități de interpretare artistică (spectacole)",
  "9002": "Activități suport pentru interpretare artistică (spectacole)",
  "9003": "Activități de creație artistică",
  "9004": "Activități de gestionare a sălilor de spectacole",
  "9101": "Activități ale bibliotecilor și arhivelor",
  "9102": "Activități ale muzeelor",
  "9103": "Gestionarea monumentelor, clădirilor istorice și a altor obiective de interes turistic",
  "9104": "Activități ale grădinilor zoologice, botanice și ale rezervațiilor naturale",
  "9200": "Activități de jocuri de noroc și pariuri",
  "9311": "Activități ale bazelor sportive",
  "9312": "Activități ale cluburilor sportive",
  "9313": "Activități ale centrelor de fitness",
  "9319": "Alte activități sportive",
  "9321": "Bâlciuri și parcuri de distracții",
  "9329": "Alte activități recreative și distractive n.c.a.",
  "9411": "Activități ale organizațiilor patronale și profesionale",
  "9412": "Activități ale organizațiilor profesionale",
  "9420": "Activități ale sindicatelor salariaților",
  "9491": "Activități ale organizațiilor religioase",
  "9499": "Activități ale altor organizații n.c.a.",
  "9511": "Repararea calculatoarelor și a echipamentelor periferice",
  "9512": "Repararea echipamentelor de comunicații",
  "9521": "Repararea aparatelor electronice de uz casnic",
  "9522": "Repararea dispozitivelor de uz gospodăresc și a echipamentelor pentru casă și grădină",
  "9523": "Repararea încălțămintei și a articolelor din piele",
  "9524": "Repararea mobilei și a furniturilor casnice",
  "9525": "Repararea ceasurilor și a bijuteriilor",
  "9529": "Repararea articolelor de uz personal și gospodăresc n.c.a.",
  "9601": "Spălarea și curățarea (uscată) a articolelor textile și a produselor din blană",
  "9602": "Coafură și alte activități de înfrumusețare",
  "9603": "Activități de pompe funebre și similare",
  "9604": "Activități de întreținere corporală",
  "9609": "Alte activități de servicii n.c.a.",
  "9700": "Activități ale gospodăriilor private în calitate de angajator de personal casnic",
};

/**
 * Get CAEN description for a code. Returns null if not found.
 */
export function getCaenDescription(code: string | null | undefined): string | null {
  if (!code) return null;
  const clean = code.replace(/[^0-9]/g, "").padStart(4, "0");
  return CAEN_CODES[clean] || null;
}

export default CAEN_CODES;
